version: '3.8'

services:
  # 1. Database MySQL
  mysql_db:
    image: mysql:8.0
    container_name: cpanel_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_backend
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_cpanel_data:/var/lib/mysql

  # 2. Single 1-Slot Node.js App Container (Phusion Passenger Simulation running app.js)
  cpanel_app:
    build:
      context: .
      dockerfile: Dockerfile.cpanel
    container_name: cpanel_node_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://testuser:testpassword@mysql_db:3306/test_backend"
      JWT_SECRET: "secret-key-super-aman-anda"
      NEXT_PUBLIC_API_URL: "http://localhost:3000/api"
    depends_on:
      - mysql_db

volumes:
  mysql_cpanel_data:
